// crossAPI获取信息的静态数据
import { create } from 'zustand';
import { produce } from 'immer';


export interface StaticDataStoreState {
    callingInfo: any;
    clientBusiInfo: any;
    serialNo: any;
    getAgentState: any;
}
const initCrossAPIStaticDataState: StaticDataStoreState = {
    callingInfo: {// 通话信息
        CTICallId: "94fd5988-cf26-XXXX-****-a7ec5ab6e2e4",
        LanuchCooperateFlag: "1",
        QASFlag: "1",
        VoNR: "0",
        assChannelMap: { '135********': {} },
        audioBeginTime: "2026-05-13 10:00:54",
        businessScene: "",
        callFeature: 7,
        callFeatureVal: "人工",
        callId: "94fd5988-cf26-XXXX-****-a7ec5ab6e2e4",
        callIdDsn: "94fd5988-cf26-XXXX-****-a7ec5ab6e2e4",
        callIdHandle: "",
        callIdServer: "",
        callIdTime: "",
        callMediaType: "1",
        callOutModule: "ngfv",
        callOutMsgInfo: {},
        callOutSourceType: "1",
        callOutTaskId: "",
        callProvId: "371",
        callType: "1",
        calldataExt2: "",
        calledNo: "135********",
        callerNo: "10086",
        callingCountCurDay: 0,
        callingCountTwo: 0,
        ccId: "37110086",
        channelID: "5",
        channelName: "语音",
        channelNum: "10086",
        chgScene: "",
        cipCheckFlagMap: {},
        cipCheckTypeMap: {},
        cipherCheckProcess: {},
        clientInfoMap: { '135********': {} },
        contactId: "2026****XXXX461271XXXX852",
        contactStartTime: "2026-05-13 10:00:54",
        countAlertStatus: false,
        ctiId: "10028",
        currentMediaType: 5,
        custFlagStatus: true,
        customerID: "",
        customerTagId: "",
        customerTagName: "",
        destProvId: "00030009",
        displayNo: "",
        emptyStr: "",
        extStr: "",
        faceCheckDestructIdCardInfoMap: {},
        fotnCharAttrVal: "ngfv",
        hasRecordFile: "1",
        haveFaceCheck: {},
        ifTm: "1",
        initCollaborationNum: 0,
        intoLabor: "",
        isNet: "0",
        isSupport5gMsg: true,
        isSupportUpgradeVideo: "3",
        lgId: "",
        mediaType: 5,
        mediaTypeName: "语音",
        multiAccountList: [],
        notCloseCardStatus: "",
        orgicalledNum: "135********",
        origCustNum: "135********",
        phoneNumber: "10086",
        popupsNumMap: {},
        realCallType: "1",
        recordFile: "uploadRecordFile.mp3",
        serialNo: "2026****XXXX461271XXXX852",
        serviceTypeId: "haytck",
        sessionResultList: [],
        sessionValidationInfo: {},
        sessionValidationInfoNew: {},
        skillDesc: "",
        skillId: "",
        smsRandomCode: {},
        sourceChannel: "热线呼出",
        specialAgentState: "",
        startRingTime: "2026-05-13 10:00:46",
        subcontractRelation: "",
        subsNumber: "135********",
        subsNumberCheckMap: {},
        supportCollaborationFlag: true,
        taskPlanID: "",
        taskTypeConfigId: "",
        tranProvId: "0371",
        transferFlagZK: "",
        unifiedCode: "00169****TTQ50",
        upgradeVideo: false,
        vCard: "0",
        vdnId: "1",
        voiceId: "",
        voiceprintRecording: "N",
    },
    getAgentState: { // 通话状态
        agentState: "", // 7表示在通话中
        waitState: "0"
    },
    clientBusiInfo: {
        bean: {
            accessDate: "2016-08-06 11:46:22",
            accountManager: "",
            accountManagerTel: "",
            accoutDay: "",
            brandLevelCode: "",
            brandLevelName: "",
            broadbandCustomer: "没有定购宽带",
            callFeatureVal: "人工",
            callTrace: null,
            callingCountCurDay: 0,
            callingCountTwo: 0,
            carrierTag: "0",
            carrierType: "",
            channelId: "5",
            channelname: "语音",
            cityNm: "",
            collectionStatus: "",
            creditValue: "0.00",
            curFee: "",
            curFeeTotal: "",
            curPlanId: "",
            curPlanName: "",
            custgBase: [],
            customerAssignmentCode: "0371",
            customerGrade: "三星普通用户",
            customerName: "王**",
            customerTagId: "",
            customerTagName: "",
            distrtCode: "",
            email: "",
            endTime: "",
            ext2: "PIX21BZFXC2",
            flag4G: "",
            flag5G: "0",
            homePageClentBeansData: null,
            homePageClientData: null,
            importantCustomer: "",
            insightTags: { LZYZXALL0115868: "否", LZYZXUTS0302980: "是", LZYZXUTS0302985: "否", LZYZXUTS0302983: "否", LZYZXUTS0155786: "否", },
            instantMarketFlag: "流量饱和超八成",
            isAuspicious: "否",
            isExistMarket: "否",
            isSupport5gMsg: true,
            mobilTreasuryVerification: "2",
            msisdn: "135********",
            mtopFctyName: "中国移动",
            mtopFctyType: "002",
            netId: "002",
            netIdDesc: "中国移动",
            nextPlanId: "",
            nextPlanName: "",
            numAssignmentCode: "0371",
            openStatus: "",
            orgicalledNum: "135********",
            oweFee: "",
            phoneNumber: "135********",
            provCode: "",
            provNm: "河南郑州0371",
            province: "371",
            provinceName: "河南",
            realFee: "",
            realNameInfo: "",
            region: "373",
            regionName: "郑州",
            resultCode: "100001",
            specialCustom: "",
            starLevel: "三星",
            starScore: "",
            starTime: "",
            startTime: "",
            subsNumber: "135********",
            tariffPackages: "移动流量王套餐基础版",
            tariffPackagesCode: "100168004540",
            telNumStarCode: "09",
            telNumState: "正常",
            telNumStateCode: "1",
            terminalModel: "",
            terminalType: "",
            threeViewTagsInfo: { cardSlotView: [], saturationView: [], fusionView: [] },
            userAdd: "",
            userBegin: "",
            userBrand: "",
            userBrandVal: "",
            userId: "",
            userIdVal: "",
            userLevel: "40",
            userLevelVal: "",
            userName: "",
            userNum: "",
            userStatus: "",
            userStatusVal: "",
            volteFlag: "",
            zipCode: "",
            zkCustomType: ",",
        }
    },
    serialNo: '2026****XXXX461271XXXX852',
};
export const CrossAPIStaticData = create<
    StaticDataStoreState & {
        setStaticData: () => void;
    }
>((set) => ({
    ...initCrossAPIStaticDataState,
    // 更新数据
    setStaticData: () =>
        set(
            produce((draft) => {

            }),
        ),

}));
